apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dvss-apps-ns-dev

namePrefix: 'dev-'

images:
- name: xyz/details-test
  newName: apoorva6777/dvss-backend-microservice-boilerplate
  newTag: latest

replicas:
- name: nest-ms-deployment
  count: 1

patches:
- target:
    kind: HorizontalPodAutoscaler
    name: dev-nest-ms-deployment-hpa
  patch: |-
    - op: replace
      path: /metadata/name
      value: nest-ms-deployment-hpa
    - op: replace
      path: /spec/minReplicas
      value: "1"

- target:
    kind: Deployment
    name: nest-ms-deployment
  patch: |-
    - op: replace
      path: /metadata/name
      value: nest-ms-deployment
    - op: replace
      path: /spec/template/metadata/labels/app
      value: nest-ms-dev
    - op: replace
      path: /spec/selector/matchLabels/app
      value: nest-ms-dev

- target:
    kind: AuthorizationPolicy
    name: productpage-viewer-1
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: dvss-apps-ns-dev
    - op: replace
      path: /spec/selector/matchLabels/app
      value: nest-ms-dev
- target:
    kind: AuthorizationPolicy
    name: productpage-viewer
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: dvss-apps-ns-dev
    - op: replace
      path: /spec/targetRefs/0/name
      value: dev-nest-ms-service

- target:
    kind: ClusterRoleBinding
    name: dev-sa-crb
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: dvss-apps-ns-dev

- target:
    kind: Ingress
    name: nest-ms-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: onboarding.dev.com
- target:
    kind: Service
    name: nest-ms-service
  patch: |-
    - op: replace
      path: /spec/selector/app
      value: nest-ms-dev


- target:
    kind: Gateway
    name: nest-ms-gateway
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: dvss-apps-ns-dev
    - op: replace
      path: /spec/servers/0/hosts/0
      value: onboarding.dev.com
- target:
    kind: VirtualService
    name: nest-ms-virtualservice
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: dvss-apps-ns-dev
    - op: replace
      path: /spec/hosts/0
      value: onboarding.dev.com
    - op: replace
      path: /spec/gateways/0
      value: dev-nest-ms-gateway
    - op: replace
      path: /spec/http/0/route/0/destination/host
      value: dev-nest-ms-service
