apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: staging

namePrefix: 'staging-'

images:
- name: xyz/details-test
  newName: iad.ocir.io/idmaqhrbiuyo/nest-readiness-check
  newTag: v0.0.2

replicas:
- name: nest-ms-deployment
  count: 1

patches:
- target:
    kind: HorizontalPodAutoscaler
    name: staging-nest-ms-deployment-hpa
  patch: |-
    - op: replace
      path: /metadata/name
      value: nest-ms-deployment-hpa
    - op: replace
      path: /spec/minReplicas
      value: "1"

- target:
    kind: Deployment
    name: nest-ms-deployment
  patch: |-
    - op: replace
      path: /metadata/name
      value: nest-ms-deployment
    - op: replace
      path: /spec/template/metadata/labels/app
      value: nest-ms-staging
    - op: replace
      path: /spec/selector/matchLabels/app
      value: nest-ms-staging

- target:
    kind: AuthorizationPolicy
    name: productpage-viewer-1
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: staging
    - op: replace
      path: /spec/selector/matchLabels/app
      value: nest-ms-staging
- target:
    kind: AuthorizationPolicy
    name: productpage-viewer
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: staging
    - op: replace
      path: /spec/targetRefs/0/name
      value: staging-nest-ms-service

- target:
    kind: ClusterRoleBinding
    name: sa-crb
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: staging

- target:
    kind: Ingress
    name: nest-ms-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: onboarding.staging.com
- target:
    kind: Service
    name: nest-ms-service
  patch: |-
    - op: replace
      path: /spec/selector/app
      value: nest-ms-staging
