apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dvss-apps-ns-qa

namePrefix: 'qa-'

images:
- name: xyz/details-test
  newName: apoorva6777/dvss-backend-microservice-boilerplate
  newTag: latest

replicas:
- name: nest-ms-deployment
  count: 1

patches:
- target:
    kind: HorizontalPodAutoscaler
    name: qa-nest-ms-deployment-hpa
  patch: |-
    - op: replace
      path: /metadata/name
      value: nest-ms-deployment-hpa
    - op: replace
      path: /spec/minReplicas
      value: "1"

- target:
    kind: Deployment
    name: nest-ms-deployment
  patch: |-
    - op: replace
      path: /metadata/name
      value: nest-ms-deployment
    - op: replace
      path: /spec/template/metadata/labels/app
      value: nest-ms-qa
    - op: replace
      path: /spec/selector/matchLabels/app
      value: nest-ms-qa

- target:
    kind: AuthorizationPolicy
    name: productpage-viewer-1
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: dvss-apps-ns-qa
    - op: replace
      path: /spec/selector/matchLabels/app
      value: nest-ms-qa
- target:
    kind: AuthorizationPolicy
    name: productpage-viewer
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: dvss-apps-ns-qa
    - op: replace
      path: /spec/targetRefs/0/name
      value: qa-nest-ms-service

- target:
    kind: ClusterRoleBinding
    name: qa-sa-crb
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: dvss-apps-ns-qa

- target:
    kind: Ingress
    name: nest-ms-ingress
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: onboarding.qa.com
- target:
    kind: Service
    name: nest-ms-service
  patch: |-
    - op: replace
      path: /spec/selector/app
      value: nest-ms-qa
